# roles/frontend-deployment/tasks/main.yml
---
- name: Pull image from repository
  docker_image:
    name: cattherinemirobe/yolo_frontend:v1.0.0.0
    source: pull

- name: Create Node.js frontend Container
  docker_container:
    name: cattherinemirobe_yolo_frontend
    image: cattherinemirobe/yolo_frontend:v1.0.0.0
    networks:
      - name: app-net
    ports:
      - "3000:3000"
    command: "npm start"
    restart_policy: unless-stopped
  become: true