apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: a25vd2Vub2Jpc28=  # base64 encoded value for username
  MONGO_INITDB_ROOT_PASSWORD: RFdLTWlQazdyUHpFT0tJZA==  # base64 encoded value for password
  MONGO_INITDB_DATABASE: eW9sb215  # base64 encoded value for the dbname
