---
- name: Pull image from repository
  docker_image:
    name: cattherinemirobe/yolo_backend:v1.0.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: cattherinemirobe_yolo_backend
    image: cattherinemirobe/yolo_backend:v1.0.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
    restart_policy: unless-stopped
  become: yes